# Generated by Django 5.1.6 on 2025-03-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0001_initial'),
    ]

    operations = [
    ]
