# Generated by Django 5.1.6 on 2025-03-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20250311_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
