# Generated by Django 5.1.6 on 2025-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
